package output

import (
	"context"
	"encoding/json"
	"net/http"
	"runtime"
	"strings"
	"sync"
	"time"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/collectors"
	"github.com/prometheus/client_golang/prometheus/promhttp"
	"github.com/rs/zerolog/log"

	"github.com/xoelrdgz/logradar/internal/domain"
)

var (
	Version   = "dev"
	Commit    = "unknown"
	BuildTime = "unknown"
)

type PrometheusMetrics struct {
	registry *prometheus.Registry

	buildInfo *prometheus.GaugeVec

	linesProcessedTotal  prometheus.Counter
	linesProcessedByType *prometheus.CounterVec
	alertsGeneratedTotal *prometheus.CounterVec
	threatsDetectedTotal *prometheus.CounterVec

	processingErrorsTotal *prometheus.CounterVec
	parseErrorsTotal      prometheus.Counter
	parseErrorsByReason   *prometheus.CounterVec
	queueOverflowTotal    prometheus.Counter
	alerterErrorsTotal    *prometheus.CounterVec

	processingDuration        *prometheus.HistogramVec
	processingDurationSummary *prometheus.SummaryVec

	queueUtilization  prometheus.GaugeFunc
	workerUtilization prometheus.GaugeFunc

	queueSize         prometheus.GaugeFunc
	queueCapacity     prometheus.GaugeFunc
	activeWorkers     prometheus.GaugeFunc
	configuredWorkers prometheus.GaugeFunc
	pendingLines      prometheus.GaugeFunc

	memoryAllocBytes    prometheus.GaugeFunc
	memorySysBytes      prometheus.GaugeFunc
	memoryHeapObjects   prometheus.GaugeFunc
	goroutinesCount     prometheus.GaugeFunc
	gcPauseTotalSeconds prometheus.CounterFunc
	gcLastPauseSeconds  prometheus.GaugeFunc

	sloLatencyBucket      *prometheus.CounterVec
	sloAvailabilityTotal  prometheus.Counter
	sloAvailabilityErrors prometheus.Counter

	linesPerSecond      prometheus.GaugeFunc
	bytesProcessed      prometheus.Counter
	totalLinesGauge     prometheus.GaugeFunc
	maliciousLinesGauge prometheus.GaugeFunc
	cleanLinesGauge     prometheus.GaugeFunc

	uptimeSeconds       prometheus.CounterFunc
	lastSuccessfulParse prometheus.Gauge
	healthCheckDuration prometheus.Histogram

	detectionsByType      *prometheus.CounterVec
	detectionsBySeverity  *prometheus.CounterVec
	riskScoreHistogram    prometheus.Histogram
	threatIntelEntries    prometheus.Gauge
	threatIntelLastReload prometheus.Gauge
	threatIntelFeedErrors prometheus.Gauge

	internalMetrics *domain.AnalysisMetrics
	startTime       time.Time

	server         *http.Server
	mu             sync.Mutex
	readinessCheck func() (bool, string)
	queueStats     func() (int, int)
}

type MetricsConfig struct {
	Port            string
	Path            string
	HealthPath      string
	LivePath        string
	EnableGoMetrics bool
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		Port:            ":9090",
		Path:            "/metrics",
		HealthPath:      "/ready",
		LivePath:        "/live",
		EnableGoMetrics: true,
	}
}

func NewPrometheusMetrics(namespace string, internalMetrics *domain.AnalysisMetrics) *PrometheusMetrics {
	if namespace == "" {
		namespace = "logradar"
	}

	m := &PrometheusMetrics{
		registry:        prometheus.NewRegistry(),
		internalMetrics: internalMetrics,
		startTime:       time.Now(),
	}

	m.buildInfo = prometheus.NewGaugeVec(prometheus.GaugeOpts{
		Namespace: namespace,
		Name:      "build_info",
		Help:      "Build information including version, commit and build time",
	}, []string{"version", "commit", "build_time", "go_version"})
	m.buildInfo.WithLabelValues(Version, Commit, BuildTime, runtime.Version()).Set(1)

	m.linesProcessedTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Namespace: namespace,
		Subsystem: "pipeline",
		Name:      "lines_processed_total",
		Help:      "Total number of log lines processed",
	})

	m.linesProcessedByType = prometheus.NewCounterVec(prometheus.CounterOpts{
		Namespace: namespace,
		Subsystem: "pipeline",
		Name:      "lines_by_result_total",
		Help:      "Log lines processed by result type (clean, malicious, error)",
	}, []string{"result"})

	m.alertsGeneratedTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Namespace: namespace,
		Subsystem: "detection",
		Name:      "alerts_total",
		Help:      "Total alerts generated by severity level",
	}, []string{"level"})

	m.threatsDetectedTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Namespace: namespace,
		Subsystem: "detection",
		Name:      "threats_total",
		Help:      "Total threats detected by type",
	}, []string{"type"})

	m.processingErrorsTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Namespace: namespace,
		Subsystem: "pipeline",
		Name:      "errors_total",
		Help:      "Total processing errors by error type",
	}, []string{"error_type"})

	m.parseErrorsTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Namespace: namespace,
		Subsystem: "parser",
		Name:      "errors_total",
		Help:      "Total log line parsing errors",
	})

	m.parseErrorsByReason = prometheus.NewCounterVec(prometheus.CounterOpts{
		Namespace: namespace,
		Subsystem: "parser",
		Name:      "errors_by_reason_total",
		Help:      "Total log line parsing errors by reason",
	}, []string{"reason"})

	m.queueOverflowTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Namespace: namespace,
		Subsystem: "pipeline",
		Name:      "queue_overflow_total",
		Help:      "Total items dropped due to queue overflow",
	})

	m.alerterErrorsTotal = prometheus.NewCounterVec(prometheus.CounterOpts{
		Namespace: namespace,
		Subsystem: "alerter",
		Name:      "errors_total",
		Help:      "Total alerter send errors by output",
	}, []string{"output"})

	m.processingDuration = prometheus.NewHistogramVec(prometheus.HistogramOpts{
		Namespace: namespace,
		Subsystem: "pipeline",
		Name:      "processing_duration_seconds",
		Help:      "Time spent processing each log line",
		Buckets: []float64{
			0.00001, 0.00005, 0.0001, 0.0005, 0.001,
			0.005, 0.01, 0.025, 0.05, 0.1,
			0.25, 0.5, 1.0,
		},
	}, []string{"stage"})

	m.processingDurationSummary = prometheus.NewSummaryVec(prometheus.SummaryOpts{
		Namespace: namespace,
		Subsystem: "pipeline",
		Name:      "processing_duration_quantiles",
		Help:      "Processing duration quantiles (p50, p90, p99)",
		Objectives: map[float64]float64{
			0.5:  0.05,
			0.9:  0.01,
			0.99: 0.001,
		},
		MaxAge:     1 * time.Minute,
		AgeBuckets: 3,
	}, []string{"stage"})

	m.queueUtilization = prometheus.NewGaugeFunc(prometheus.GaugeOpts{
		Namespace: namespace,
		Subsystem: "pipeline",
		Name:      "queue_utilization_ratio",
		Help:      "Current queue utilization (0.0-1.0)",
	}, func() float64 {
		size, capacity := m.currentQueueStats()
		if capacity > 0 {
			return float64(size) / float64(capacity)
		}
		return 0
	})

	m.queueSize = prometheus.NewGaugeFunc(prometheus.GaugeOpts{
		Namespace: namespace,
		Subsystem: "pipeline",
		Name:      "queue_size_current",
		Help:      "Current number of items in the processing queue",
	}, func() float64 {
		size, _ := m.currentQueueStats()
		return float64(size)
	})

	m.queueCapacity = prometheus.NewGaugeFunc(prometheus.GaugeOpts{
		Namespace: namespace,
		Subsystem: "pipeline",
		Name:      "queue_capacity",
		Help:      "Configured capacity of the processing queue",
	}, func() float64 {
		_, capacity := m.currentQueueStats()
		return float64(capacity)
	})

	m.activeWorkers = prometheus.NewGaugeFunc(prometheus.GaugeOpts{
		Namespace: namespace,
		Subsystem: "pipeline",
		Name:      "workers_active",
		Help:      "Number of workers currently processing",
	}, func() float64 {
		if internalMetrics != nil {
			return float64(internalMetrics.GetSnapshot().ActiveWorkers)
		}
		return 0
	})

	m.memoryAllocBytes = prometheus.NewGaugeFunc(prometheus.GaugeOpts{
		Namespace: namespace,
		Subsystem: "runtime",
		Name:      "memory_alloc_bytes",
		Help:      "Current heap allocation in bytes",
	}, func() float64 {
		var stats runtime.MemStats
		runtime.ReadMemStats(&stats)
		return float64(stats.Alloc)
	})

	m.memorySysBytes = prometheus.NewGaugeFunc(prometheus.GaugeOpts{
		Namespace: namespace,
		Subsystem: "runtime",
		Name:      "memory_sys_bytes",
		Help:      "Total memory obtained from system",
	}, func() float64 {
		var stats runtime.MemStats
		runtime.ReadMemStats(&stats)
		return float64(stats.Sys)
	})

	m.memoryHeapObjects = prometheus.NewGaugeFunc(prometheus.GaugeOpts{
		Namespace: namespace,
		Subsystem: "runtime",
		Name:      "heap_objects",
		Help:      "Number of allocated heap objects",
	}, func() float64 {
		var stats runtime.MemStats
		runtime.ReadMemStats(&stats)
		return float64(stats.HeapObjects)
	})

	m.goroutinesCount = prometheus.NewGaugeFunc(prometheus.GaugeOpts{
		Namespace: namespace,
		Subsystem: "runtime",
		Name:      "goroutines_count",
		Help:      "Current number of goroutines",
	}, func() float64 {
		return float64(runtime.NumGoroutine())
	})

	m.gcLastPauseSeconds = prometheus.NewGaugeFunc(prometheus.GaugeOpts{
		Namespace: namespace,
		Subsystem: "runtime",
		Name:      "gc_last_pause_seconds",
		Help:      "Duration of most recent GC pause",
	}, func() float64 {
		var stats runtime.MemStats
		runtime.ReadMemStats(&stats)
		if stats.NumGC == 0 {
			return 0
		}
		return float64(stats.PauseNs[(stats.NumGC+255)%256]) / 1e9
	})

	m.sloLatencyBucket = prometheus.NewCounterVec(prometheus.CounterOpts{
		Namespace: namespace,
		Subsystem: "slo",
		Name:      "latency_bucket_total",
		Help:      "Requests by latency SLO bucket (fast <1ms, normal <10ms, slow <100ms, very_slow >=100ms)",
	}, []string{"bucket"})

	m.sloAvailabilityTotal = prometheus.NewCounter(prometheus.CounterOpts{
		Namespace: namespace,
		Subsystem: "slo",
		Name:      "requests_successful_total",
		Help:      "Total successfully processed requests (for availability SLO)",
	})

	m.sloAvailabilityErrors = prometheus.NewCounter(prometheus.CounterOpts{
		Namespace: namespace,
		Subsystem: "slo",
		Name:      "requests_failed_total",
		Help:      "Total failed requests (for availability SLO)",
	})

	m.linesPerSecond = prometheus.NewGaugeFunc(prometheus.GaugeOpts{
		Namespace: namespace,
		Subsystem: "pipeline",
		Name:      "throughput_lines_per_second",
		Help:      "Current processing throughput in lines per second",
	}, func() float64 {
		if internalMetrics != nil {
			return internalMetrics.GetSnapshot().LinesPerSecond
		}
		return 0
	})

	m.bytesProcessed = prometheus.NewCounter(prometheus.CounterOpts{
		Namespace: namespace,
		Subsystem: "pipeline",
		Name:      "bytes_processed_total",
		Help:      "Total bytes of log data processed",
	})

	m.totalLinesGauge = prometheus.NewGaugeFunc(prometheus.GaugeOpts{
		Namespace: namespace,
		Subsystem: "pipeline",
		Name:      "valid_lines_total",
		Help:      "Total number of log lines processed (accurate count from internal metrics)",
	}, func() float64 {
		if internalMetrics != nil {
			return float64(internalMetrics.GetSnapshot().TotalLinesProcessed)
		}
		return 0
	})

	m.maliciousLinesGauge = prometheus.NewGaugeFunc(prometheus.GaugeOpts{
		Namespace: namespace,
		Subsystem: "pipeline",
		Name:      "lines_malicious_total",
		Help:      "Total number of malicious log lines detected (accurate count from internal metrics)",
	}, func() float64 {
		if internalMetrics != nil {
			return float64(internalMetrics.GetSnapshot().MaliciousLines)
		}
		return 0
	})

	m.cleanLinesGauge = prometheus.NewGaugeFunc(prometheus.GaugeOpts{
		Namespace: namespace,
		Subsystem: "pipeline",
		Name:      "lines_clean_total",
		Help:      "Total number of clean log lines (total - malicious)",
	}, func() float64 {
		if internalMetrics != nil {
			snap := internalMetrics.GetSnapshot()
			return float64(snap.TotalLinesProcessed - snap.MaliciousLines)
		}
		return 0
	})

	m.uptimeSeconds = prometheus.NewCounterFunc(prometheus.CounterOpts{
		Namespace: namespace,
		Name:      "uptime_seconds_total",
		Help:      "Total uptime of the logradar instance",
	}, func() float64 {
		return time.Since(m.startTime).Seconds()
	})

	m.lastSuccessfulParse = prometheus.NewGauge(prometheus.GaugeOpts{
		Namespace: namespace,
		Subsystem: "pipeline",
		Name:      "last_successful_parse_timestamp",
		Help:      "Unix timestamp of last successfully parsed log line",
	})

	m.healthCheckDuration = prometheus.NewHistogram(prometheus.HistogramOpts{
		Namespace: namespace,
		Name:      "health_check_duration_seconds",
		Help:      "Time taken to perform health checks",
		Buckets:   prometheus.ExponentialBuckets(0.001, 2, 10),
	})

	m.detectionsByType = prometheus.NewCounterVec(prometheus.CounterOpts{
		Namespace: namespace,
		Subsystem: "detection",
		Name:      "by_type_total",
		Help:      "Detections broken down by threat type",
	}, []string{"threat_type"})

	m.detectionsBySeverity = prometheus.NewCounterVec(prometheus.CounterOpts{
		Namespace: namespace,
		Subsystem: "detection",
		Name:      "by_severity_total",
		Help:      "Detections broken down by severity level",
	}, []string{"severity"})

	m.riskScoreHistogram = prometheus.NewHistogram(prometheus.HistogramOpts{
		Namespace: namespace,
		Subsystem: "detection",
		Name:      "risk_score_distribution",
		Help:      "Distribution of risk scores (1-10)",
		Buckets:   []float64{1, 2, 3, 4, 5, 6, 7, 8, 9, 10},
	})

	m.threatIntelEntries = prometheus.NewGauge(prometheus.GaugeOpts{
		Namespace: namespace,
		Subsystem: "threat_intel",
		Name:      "entries_loaded",
		Help:      "Threat intelligence entries loaded",
	})
	m.threatIntelLastReload = prometheus.NewGauge(prometheus.GaugeOpts{
		Namespace: namespace,
		Subsystem: "threat_intel",
		Name:      "last_reload_timestamp",
		Help:      "Unix timestamp of the last threat intelligence reload",
	})
	m.threatIntelFeedErrors = prometheus.NewGauge(prometheus.GaugeOpts{
		Namespace: namespace,
		Subsystem: "threat_intel",
		Name:      "feed_errors_total",
		Help:      "Threat intelligence feed load errors observed at startup or reload",
	})

	m.registerMetrics()

	return m
}

func (m *PrometheusMetrics) registerMetrics() {

	m.registry.MustRegister(m.buildInfo)

	m.registry.MustRegister(m.linesProcessedTotal)
	m.registry.MustRegister(m.linesProcessedByType)
	m.registry.MustRegister(m.alertsGeneratedTotal)
	m.registry.MustRegister(m.threatsDetectedTotal)

	m.registry.MustRegister(m.processingErrorsTotal)
	m.registry.MustRegister(m.parseErrorsTotal)
	m.registry.MustRegister(m.parseErrorsByReason)
	m.registry.MustRegister(m.queueOverflowTotal)
	m.registry.MustRegister(m.alerterErrorsTotal)

	m.registry.MustRegister(m.processingDuration)
	m.registry.MustRegister(m.processingDurationSummary)

	m.registry.MustRegister(m.queueUtilization)
	m.registry.MustRegister(m.queueSize)
	m.registry.MustRegister(m.queueCapacity)
	m.registry.MustRegister(m.activeWorkers)
	m.registry.MustRegister(m.memoryAllocBytes)
	m.registry.MustRegister(m.memorySysBytes)
	m.registry.MustRegister(m.memoryHeapObjects)
	m.registry.MustRegister(m.goroutinesCount)
	m.registry.MustRegister(m.gcLastPauseSeconds)

	m.registry.MustRegister(m.sloLatencyBucket)
	m.registry.MustRegister(m.sloAvailabilityTotal)
	m.registry.MustRegister(m.sloAvailabilityErrors)

	m.registry.MustRegister(m.linesPerSecond)
	m.registry.MustRegister(m.bytesProcessed)
	m.registry.MustRegister(m.totalLinesGauge)
	m.registry.MustRegister(m.maliciousLinesGauge)
	m.registry.MustRegister(m.cleanLinesGauge)

	m.registry.MustRegister(m.uptimeSeconds)
	m.registry.MustRegister(m.lastSuccessfulParse)
	m.registry.MustRegister(m.healthCheckDuration)

	m.registry.MustRegister(m.detectionsByType)
	m.registry.MustRegister(m.detectionsBySeverity)
	m.registry.MustRegister(m.riskScoreHistogram)
	m.registry.MustRegister(m.threatIntelEntries)
	m.registry.MustRegister(m.threatIntelLastReload)
	m.registry.MustRegister(m.threatIntelFeedErrors)

	m.registry.MustRegister(collectors.NewGoCollector())
	m.registry.MustRegister(collectors.NewProcessCollector(collectors.ProcessCollectorOpts{}))
}

func (m *PrometheusMetrics) SetThreatIntelStats(entries int, lastReload time.Time, feedErrors int) {
	m.threatIntelEntries.Set(float64(entries))
	if !lastReload.IsZero() {
		m.threatIntelLastReload.Set(float64(lastReload.Unix()))
	}
	m.threatIntelFeedErrors.Set(float64(feedErrors))
}

func (m *PrometheusMetrics) SetQueueStatsFunc(fn func() (int, int)) {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.queueStats = fn
}

func (m *PrometheusMetrics) currentQueueStats() (int, int) {
	m.mu.Lock()
	fn := m.queueStats
	m.mu.Unlock()
	if fn == nil {
		return 0, 0
	}
	return fn()
}

func (m *PrometheusMetrics) IncrementLinesProcessed() {
	m.linesProcessedTotal.Inc()
	m.sloAvailabilityTotal.Inc()
}

func (m *PrometheusMetrics) IncrementLinesProcessedByResult(result string) {
	m.linesProcessedTotal.Inc()
	m.linesProcessedByType.WithLabelValues(result).Inc()
	if result == "error" {
		m.sloAvailabilityErrors.Inc()
		return
	}
	m.sloAvailabilityTotal.Inc()
}

func (m *PrometheusMetrics) IncrementThreats(threatType domain.ThreatType) {
	m.threatsDetectedTotal.WithLabelValues(string(threatType)).Inc()
	m.detectionsByType.WithLabelValues(string(threatType)).Inc()
}

func (m *PrometheusMetrics) ObserveProcessingTime(seconds float64) {
	m.processingDuration.WithLabelValues("total").Observe(seconds)
	m.processingDurationSummary.WithLabelValues("total").Observe(seconds)

	switch {
	case seconds < 0.001:
		m.sloLatencyBucket.WithLabelValues("fast").Inc()
	case seconds < 0.01:
		m.sloLatencyBucket.WithLabelValues("normal").Inc()
	case seconds < 0.1:
		m.sloLatencyBucket.WithLabelValues("slow").Inc()
	default:
		m.sloLatencyBucket.WithLabelValues("very_slow").Inc()
	}

	m.lastSuccessfulParse.SetToCurrentTime()
}

func (m *PrometheusMetrics) ObserveProcessingTimeByStage(stage string, seconds float64) {
	m.processingDuration.WithLabelValues(stage).Observe(seconds)
	m.processingDurationSummary.WithLabelValues(stage).Observe(seconds)
}

func (m *PrometheusMetrics) IncrementParseErrors() {
	m.parseErrorsTotal.Inc()
	m.sloAvailabilityErrors.Inc()
	m.processingErrorsTotal.WithLabelValues("parse").Inc()
}

func (m *PrometheusMetrics) IncrementParseErrorByReason(reason string) {
	if reason == "" {
		reason = "unknown"
	}
	m.parseErrorsByReason.WithLabelValues(normalizeMetricReason(reason)).Inc()
}

func (m *PrometheusMetrics) IncrementAlerterErrors(output string) {
	if output == "" {
		output = "unknown"
	}
	m.alerterErrorsTotal.WithLabelValues(output).Inc()
	m.processingErrorsTotal.WithLabelValues("alerter_error").Inc()
	m.sloAvailabilityErrors.Inc()
}

func normalizeMetricReason(reason string) string {
	reason = strings.ToLower(strings.TrimSpace(reason))
	if reason == "" {
		return "unknown"
	}
	var b strings.Builder
	for _, r := range reason {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
			continue
		}
		b.WriteByte('_')
		if b.Len() >= 80 {
			break
		}
	}
	return strings.Trim(b.String(), "_")
}

func (m *PrometheusMetrics) IncrementProcessingErrors(errorType string) {
	m.processingErrorsTotal.WithLabelValues(errorType).Inc()
	m.sloAvailabilityErrors.Inc()
}

func (m *PrometheusMetrics) IncrementQueueOverflow() {
	m.queueOverflowTotal.Inc()
	m.processingErrorsTotal.WithLabelValues("overflow").Inc()
}

func (m *PrometheusMetrics) AddBytesProcessed(bytes int64) {
	m.bytesProcessed.Add(float64(bytes))
}

func (m *PrometheusMetrics) RecordAlert(alert *domain.Alert) {
	if alert == nil {
		return
	}

	level := string(alert.Level)
	threatType := string(alert.ThreatType)

	m.alertsGeneratedTotal.WithLabelValues(level).Inc()
	m.threatsDetectedTotal.WithLabelValues(threatType).Inc()
	m.detectionsByType.WithLabelValues(threatType).Inc()
	m.detectionsBySeverity.WithLabelValues(level).Inc()
	m.riskScoreHistogram.Observe(float64(alert.RiskScore))

}

func (m *PrometheusMetrics) RecordHealthCheck(duration time.Duration) {
	m.healthCheckDuration.Observe(duration.Seconds())
}

func (m *PrometheusMetrics) OnAlert(alert *domain.Alert) {
	m.RecordAlert(alert)
}

func (m *PrometheusMetrics) SetReadinessCheck(check func() (bool, string)) {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.readinessCheck = check
}

func (m *PrometheusMetrics) StartServer(config MetricsConfig) error {
	m.mu.Lock()
	defer m.mu.Unlock()

	mux := http.NewServeMux()

	mux.Handle(config.Path, promhttp.HandlerFor(m.registry, promhttp.HandlerOpts{
		EnableOpenMetrics:   true,
		MaxRequestsInFlight: 10,
	}))

	mux.HandleFunc(config.HealthPath, func(w http.ResponseWriter, r *http.Request) {
		start := time.Now()
		defer func() {
			m.RecordHealthCheck(time.Since(start))
		}()

		ready := true
		reason := "ready"
		m.mu.Lock()
		readinessCheck := m.readinessCheck
		m.mu.Unlock()
		if readinessCheck != nil {
			ready, reason = readinessCheck()
		}

		statusCode := http.StatusOK
		status := "ready"
		if !ready {
			statusCode = http.StatusServiceUnavailable
			status = "not_ready"
		}

		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(statusCode)
		_ = json.NewEncoder(w).Encode(map[string]interface{}{
			"ready":          ready,
			"status":         status,
			"reason":         reason,
			"uptime_seconds": time.Since(m.startTime).Seconds(),
		})
	})

	livePath := config.LivePath
	if livePath == "" {
		livePath = "/live"
	}
	mux.HandleFunc(livePath, func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		_ = json.NewEncoder(w).Encode(map[string]interface{}{
			"live":           true,
			"status":         "alive",
			"uptime_seconds": time.Since(m.startTime).Seconds(),
		})
	})

	m.server = &http.Server{
		Addr:              config.Port,
		Handler:           mux,
		ReadTimeout:       10 * time.Second,
		WriteTimeout:      10 * time.Second,
		IdleTimeout:       60 * time.Second,
		ReadHeaderTimeout: 5 * time.Second,
		MaxHeaderBytes:    1 << 16,
	}

	go func() {
		log.Info().
			Str("addr", config.Port).
			Str("metrics_path", config.Path).
			Str("health_path", config.HealthPath).
			Str("live_path", livePath).
			Str("version", Version).
			Msg("Starting Prometheus metrics server")

		if err := m.server.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			log.Error().Err(err).Msg("Metrics server error")
		}
	}()

	return nil
}

func (m *PrometheusMetrics) StopServer() error {
	m.mu.Lock()
	server := m.server
	m.server = nil
	m.mu.Unlock()

	if server != nil {
		ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cancel()
		return server.Shutdown(ctx)
	}
	return nil
}

func (m *PrometheusMetrics) IncrementRequests() {
	m.IncrementLinesProcessed()
}

func (m *PrometheusMetrics) SetActiveWorkers(count int) {

}

func (m *PrometheusMetrics) SetQueueSize(size int) {

}
